# Generated by Django 5.1.6 on 2025-04-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user_bio_user_name_alter_user_email"),
        ("base", "0003_user_avatar"),
    ]

    operations = []
